gen. class image in multi-stage fix
when in multi-stage, generate class image cause this error:
```
ValueError: not enough values to unpack (expected 2, got 1)
```
due to the sequence does not contain enough elements

might doing simple fix like `x, y, *_ = [1]` where remaining assign to `_`

night not good on forward, the best solution is restart the training after generate class image